<?php
// -> commande 1,N (1 User pour N order)
user(id, email, password, firstname, lastname, birthdate, address, complements, postal_code, city, #id_order)
// -> contient, 1, N (1 order pour N order_line)
order(id, reference, date, #id_order_line)
// -> contient, 1, N (1 order_line pour N product)
order_line(id, quantity, price, #id_product)
// -> est représenté par, 1, N (1 picture pour N product)
// -> fait partie de, N, N (N category pour N product)
product(id, name, description, price, #id_category, #id_picture)
// -> représente, 1, N (N product 1 picture)
picture(id, src, alt)
// -> fait partie de, N, N (N product pour N category)
category(id, nom)
